apiVersion: v1
kind: Pod
metadata:
  name: "rest-endpoint"
  labels:
    app: irods-rest
spec:
  containers:
    - name: irods-rest
      image: "diceunc/irods-rest:4.0.2.5"
      ports:
        - name: http
          containerPort: 8080
      volumeMounts:
        - name: "rest-backend-config"
          mountPath: "/etc/irods-ext"
  volumes:
      - name: "rest-backend-config"
        secret:
          secretName: "rest-backend-config"
